### ISSUE TITLE
Docker won't start on latest

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#10]
`2023-10-05 08:14:23,736 - INFO - Template "fakestash-v2" has a new version available in the default-templates directory
Traceback (most recent call last):
  File "/emp_stash_fill/emp_stash_fill.py", line 102, in <module>
    for k,v in conf["templates"].to_dict():
ValueError: too many values to unpack (expected 2)
2023-10-05 18:49:06,514 - INFO - Template "fakestash-v2" has a new version available in the default-templates directory
Traceback (most recent call last):
  File "/emp_stash_fill/emp_stash_fill.py", line 102, in <module>
    for k,v in conf["templates"].to_dict():
ValueError: too many values to unpack (expected 2)
2023-10-06 15:14:37,431 - INFO - Template "fakestash-v2" has a new version available in the default-templates directory
Traceback (most recent call last):
  File "/emp_stash_fill/emp_stash_fill.py", line 102, in <module>
    for k,v in conf["templates"].to_dict():
ValueError: too many values to unpack (expected 2)`

**Comment by bdbenim** [comment]
Fixed in e7e1987
