### ISSUE TITLE
Exception while serving /fill

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#19]
```
`2023-10-07 13:17:42,585 - INFO - Generating submission for scened ID 59971 including screens.
2023-10-07 13:17:43,303 - ERROR - Exception while serving /fill
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 115, in generator
    yield from gen
  File "/emp_stash_fill/emp_stash_fill.py", line 344, in generate
    with Image.open(studio_img_file[1]) as img:
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmpdz7daizc.svg'
2023-10-07 13:18:06,218 - INFO - Generating submission for scened ID 59971 including screens.
2023-10-07 13:18:06,557 - ERROR - Exception while serving /fill
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 115, in generator
    yield from gen
  File "/emp_stash_fill/emp_stash_fill.py", line 344, in generate
    with Image.open(studio_img_file[1]) as img:
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmp8txhcgvf.svg'`
```

**Comment by Asparghus** [comment]
@bdbenim can we amend the suffix of those images, so when one gives an error we know which one are we talking about? 
i.e. studio_img_file = tempfile.mkstemp(suffix="-studio." + studio_img_ext)

**Comment by bdbenim** [comment]
@Asparghus 

That's not a bad idea. In this case from my googling it seems that PIL isn't the best library for svg files, and cairosvg is recommended. I think I'll add that library to avoid this error, but if you want to update those suffixes too I think it would be helpful in the future like you say.
