### ISSUE TITLE
stash port is hard-coded in .py file

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#3]
`2023-09-24 13:18:48,432 - ERROR - Exception while serving /fill
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.9/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.9/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 289, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 118, in generator
    yield from gen
  File "/emp_stash_fill/emp_stash_fill.py", line 159, in generate
    stash_response_body = stash_response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

is there a way to import your port/url to a variable instead of hardcoding in localhost:9999 ?

**Comment by bdbenim** [comment]
The URL/port in the python file is only the default if none is specified in config/config.ini. After the script is run for the first time, it will create a directory called config which holds your templates and `config.ini` file. Under the `[stash]` section you will see the options `url` and `api_key` which need to be configured for your needs. My stash instance runs on another machine, and listens over port 443, so my url setting looks like `url = https://stash.mydomain.com` for example.
