### ISSUE TITLE
Issue uploading images

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#4]
Normally no issues, but this one scene is causing problems.
2023-09-24 14:29:09,966 - INFO - Uploading cover
2023-09-24 14:29:11,293 - ERROR - Exception while serving /fill
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.9/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.9/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 289, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.9/site-packages/flask/helpers.py", line 118, in generator
    yield from gen
  File "/emp_stash_fill/emp_stash_fill.py", line 409, in generate
    cover_remote_url = img_host_upload(img_host_token, cookies, cover_file[1], cover_mime_type, cover_ext)
  File "/emp_stash_fill/emp_stash_fill.py", line 130, in img_host_upload
    return response.json()["image"]["image"]["url"]
KeyError: 'image'

**Comment by bdbenim** [comment]
I have a suspicion, as I've somewhat been expecting a bug with uploading covers based on the original code. If you go to that scene in stash and download the cover, does it use the webp extension?

**Comment by bdbenim** [comment]
Can you try saving and then manually uploading the cover to jerking.empornium.ph to see if it works? My guess is just that it might exceed the file size limit, especially since you said pulling the cover from stash fixed it - stashdb limits covers to 720p so they're unlikely to be too large. If that's the case it shouldn't be too difficult to fix the code.
The web dialogue doesn't get too specific with the steps, but your stack trace tells me that it's getting the error when it tries to upload the cover image. That's the first one it uploads, so it's possible that the screens are also problematic but it's not getting that far at this point.

**Comment by bdbenim** [comment]
Thanks! I'll update it to scale down images that are too large so you don't get this error again.

**Comment by bdbenim** [comment]
Should be resolved by commit 6dd8519
