### ISSUE TITLE
Date as a string

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#55]
Having issues when using the jinja template:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 115, in generator
    yield from gen
  File "/emp_stash_fill/emp_stash_fill.py", line 734, in generate
    title = render_template_string(TITLE_TEMPLATE, **{
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 164, in render_template_string
    return _render(app, template, context)
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
```

Looks like the current data is being pulled only as a string in the .py code?

**Comment by bdbenim** [comment]
Yes everything going to the template is a string. But the `date_format` config option should let you use whatever date format you need.
