### ISSUE TITLE
Hashlib was added in 0.8.0 but python 3.10.13 does not support hashlib.file_digest

### ISSUE THREAD

**Issue by HusariaCakes** [bdbenim/stash-empornium#61]
Gettting this traceback:
`2023-10-19 03:32:12,161 - INFO - Making torrent
2023-10-19 03:32:13,787 - INFO - Generating media info
2023-10-19 03:32:15,215 - INFO - Uploading cover
2023-10-19 03:32:15,215 - ERROR - Exception while serving /fill
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/waitress/channel.py", line 428, in service
    task.service()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 168, in service
    self.execute()
  File "/usr/local/lib/python3.10/site-packages/waitress/task.py", line 456, in execute
    for chunk in app_iter:
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 115, in generator
    yield from gen
  File "/emp_stash_fill/emp_stash_fill.py", line 839, in generate
    cover_remote_url = img_host_upload(img_host_token, cookies, cover_file[1], cover_mime_type, cover_ext)
  File "/emp_stash_fill/emp_stash_fill.py", line 324, in img_host_upload
    digest = hashlib.file_digest(f, hashlib.md5).hexdigest()
AttributeError: module 'hashlib' has no attribute 'file_digest'`

Downgrading to 0.7.0 works fine.
[hashlib.file_digest does not exist in python 3.10](https://docs.python.org/3.10/library/hashlib.html)
[It does exists in 3.11](https://docs.python.org/3.11/library/hashlib.html#file-hashing).

Can the required version of python in the dockerfile be bumped?

**Comment by HusariaCakes** [comment]
I created a pull request: https://github.com/bdbenim/stash-empornium/pull/62
